const prod = require('../../helpers/prod');

module.exports = {
  rules: {
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'curly': ['error', 'multi-line', 'consistent'],
    'default-param-last': prod(),
    'dot-location': ['error', 'property'],
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'grouped-accessor-pairs': prod(),
    'no-alert': prod(),
    'no-caller': prod(),
    'no-constructor-return': 'error',
    'no-else-return': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-floating-decimal': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-return-assign': ['error', 'except-parens'],
    'no-return-await': 'error',
    'no-self-compare': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'radix': ['error', 'always'],
    'require-await': prod(),
    'vars-on-top': 'error',
    'wrap-iife': [prod(), 'inside'],
    'yoda': [prod(), 'never'],
  },
};
